[package]
name = "sunspec"
version = "0.3.1"
edition = "2021"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "SunSpec 1.1 compliant library with tokio support"
keywords = ["sunspec", "models", "generated"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bikeshedder/sunspec"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio-modbus"]

[dependencies]
bitflags = "2.4.1"
strum = { version = "0.26.0", features = ["derive"] }
thiserror = "1.0.50"
tokio-modbus = { version = "0.11.0", optional = true }

[workspace]
members = ["sunspec-gen", "examples/*"]
