[package]
name = "sunspec"
version = "0.1.0"
edition = "2021"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool"
keywords = ["sunspec", "models", "generated"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bikeshedder/sunspec"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
tokio-modbus = "0.9.0"
tracing = "0.1.40"

[workspace]
members = [
    "sunspec-gen",
    "examples/*",
]
